package com.github.ohallors.avro.generic;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.Assert.*;

import org.junit.Test;

public class GenericRecordExamplesTest {
    @Test
    public void testSomeLibraryMethod() {
        GenericRecordExamples classUnderTest = new GenericRecordExamples();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
